rules/refinery.yaml
=> Remove cash ticks from the refinery

OpenRA.Mods.D2/make.ps1
[Open-source PowerShell](https://github.com/PowerShell/PowerShell) 🎉 allowed me to actually test this myself.
I've added the missing bracket pair that the powershell language requires.
=> Add missing body to an elseif

rules/carryall.yaml, rules/combat_tank.yaml, rules/devastator.yaml, rules/deviator.yaml, rules/frigate.yaml, rules/gun_turret.yaml, rules/harvester.yaml, rules/light_inf.yaml, rules/light_squad.yaml, rules/mcv.yaml, rules/missile_tank.yaml, rules/ornithopter.yaml, rules/quad.yaml, rules/raider.yaml, rules/repair_pad.yaml, rules/rocket_turret.yaml, rules/saboteur.yaml, rules/sandworm.yaml, rules/siege_tank.yaml, rules/sonic_tank.yaml, rules/trike.yaml, rules/trooper.yaml, rules/trooper_squad.yaml
=> Checked health and corrected wrong values not matching the original

rules/concrete.yaml
=> Fix concreteb build duration

mod.yaml
Proper fix to #29
Didn't test i'm on mobile.
=> Make the game read v2 subfolder for d2k files

mods/d2/rules/carryall.yaml, mods/d2/rules/frigate.yaml, mods/d2/rules/ornithopter.yaml
=> Give Aircraft low CruiseAltitude.

mods/d2/sequences/conyard.yaml
=> Fix ConYard upgrade cameo

mods/d2/tilesets/arrakis2.yaml
Category was renamed to Categories and is causing crash.
=> Fix map editor crash

mods/d2/sequences/combat_tank.yaml
Fixes #78 . I forgot the include the sequence changes in the related PR.
=> Fix combat tank crash

mods/d2/rules/spicebloom.yaml, mods/d2/sequences/spicebloom.yaml, mods/d2/weapons/spicebloom.yaml
Removes D2k spice bloom logic from them and makes them more like the ones from D2.
=> Fix Spicebloom

mods/d2/rules/sandworm.yaml
=> Fix sandworm sounds

mods/d2/rules/barracks.yaml, mods/d2/rules/building.yaml, mods/d2/rules/infantry.yaml, mods/d2/rules/outpost.yaml, mods/d2/rules/palace.yaml, mods/d2/rules/research_centre.yaml, mods/d2/rules/wor.yaml
I'm not sure if the SabotageThreshold: 25 and SabotageHPRemoval: 10 match the original. But what can be captured and what cannot should be matching.
=> Adjust capturing

mods/d2/sequences/explosion.yaml, mods/d2/weapons/other.yaml
=> Wall explosion crash fixup

AUTHORS, OpenRA.Mods.D2/AudioLoaders/D2VocLoader.cs, OpenRA.Mods.D2/D2LoadScreen.cs, OpenRA.Mods.D2/D2UnpackContent.cs, OpenRA.Mods.D2/FileFormats/WsaReader.cs, OpenRA.Mods.D2/SpriteLoaders/CpsD2Loader.cs, OpenRA.Mods.D2/SpriteLoaders/IcnD2Loader.cs, OpenRA.Mods.D2/SpriteLoaders/WsaD2Loader.cs, OpenRA.Mods.D2/SpriteLoaders/WsaLoader.cs, OpenRA.Mods.D2/Traits/Buildings/D2Building.cs, OpenRA.Mods.D2/Traits/Buildings/D2Concrete.cs, OpenRA.Mods.D2/Traits/Buildings/D2ConcreteOwners.cs, OpenRA.Mods.D2/Traits/D2AffectsShroud.cs, OpenRA.Mods.D2/Traits/D2RevealsShroud.cs, OpenRA.Mods.D2/Traits/PaletteEffects/D2WindtrapPaletteEffect.cs, OpenRA.Mods.D2/Traits/Render/WithTilesetBody.cs, OpenRA.Mods.D2/Traits/World/D2EditorResourceLayer.cs, OpenRA.Mods.D2/Traits/World/D2ResourceLayer.cs, OpenRA.Mods.D2/Traits/World/D2ShroudRenderer.cs, OpenRA.Mods.D2/Traits/World/D2TerrainLayer.cs, OpenRA.Mods.D2/Widgets/Logic/D2AssetBrowserLogic.cs, OpenRA.Mods.D2/Widgets/Logic/D2MissionBrowserLogic.cs, OpenRA.Mods.D2/Widgets/WsaPlayerWidget.cs, README.md, mods/d2/AUTHORS, mods/d2/mod.yaml
=> Update AUTHORS and Copyright in headers

mods/d2/rules/palettes.yaml
=> Restore 'disabled' palete

OpenRA.Mods.D2/Graphics/D2BuildingPlacementRenderable.cs, OpenRA.Mods.D2/Traits/Buildings/D2Building.cs, OpenRA.Mods.D2/Traits/Buildings/D2PlaceBuildingPreview.cs, mods/d2/rules/building.yaml, mods/d2/rules/concrete.yaml, mods/d2/rules/wall.yaml
Closes #110 
Do not draw all building sprites, just bounds rect for buildings placements
=> Add D2BuildingPlacementRenderable and D2PlaceBuildingPreview

AUTHORS
=> fix AUTHORS symlink

OpenRA.Mods.D2/ImportData/D2MapImporter.cs, OpenRA.Mods.D2/Widgets/D2SpriteWidget.cs
=> Remove references to System.Drawing

mod.config
Don't see any recent changes from playtest-20191102 in UpdateRules.
Just change ENGINE_VERSION in mod.config
=> Update OpenRA engine to release-20191117

mods/d2/rules/player.yaml
Closes #167
As mentoined in this comment https://github.com/OpenRA/d2/issues/167#issuecomment-559763436
=> Add PlayerRadarTerrain trait to Player

mods/d2/rules/world.yaml
=> Fix traits in EditorWorld

OpenRA.Mods.D2/Traits/World/D2ResourceRenderer.cs, mods/d2/rules/world.yaml
=> Add D2ResourceRenderer

mods/d2/sequences/harvester.yaml, mods/d2/sequences/vechicle_trail.yaml
=> Remove not needed blend mode switches

CONTRIBUTING.md, OpenRA.Mods.D2/Traits/Render/D2LeavesTracks.cs
=> Draw tracks for harvester

mods/d2/audio/music.yaml, mods/d2/audio/notifications.yaml, mods/d2/audio/voices.yaml
=> Guard orders

mods/d2/chrome.yaml
=> Fix scrollbar/up_arrow not found exception

OpenRA.Mods.D2/Traits/Buildings/D2Building.cs, OpenRA.Mods.D2/Traits/World/D2BuildableTerrainLayer.cs, mods/d2/rules/arrakis.yaml, mods/d2/rules/building.yaml, mods/d2/rules/concrete.yaml, mods/d2/rules/construction_yard.yaml, mods/d2/rules/world.yaml
Fixups in concrete
Fixups in Buildings and Concrete after LaysTerrain trait was removed from engine
Closes #205
=> Add D2Building
