OpenRA/d2

rules/concrete.yaml

this will fix the issue of single and quad-concrete only being allowed to get placed one time around the conyard , thus making expanding not possible ...  as discussed in #9
the idea here is to allow concrete to get placed in a 3-cell range around a placed building ... but still only allow buildings to get placed one after another 
though it is not the "original" concrete & building placement (endless one by one and buildings can get attached to it) it does add a more "dune-ish" way of expanding while keep basecreeping at a minimum (noticeable on the AI - behaviour)

Update concrete.yaml to fix base-expanding

---

mods/d2/rules/palace.yaml

D2 doesn't have a anim for palace firing the Death Hand, so existence of this trait causing crash saying Palace doesn't have a sequence named active.

Remove WithNukeLaunchOverlay from palace

---

mods/d2/rules/barracks.yaml
mods/d2/rules/concrete.yaml
mods/d2/rules/construction_yard.yaml
mods/d2/rules/gun_turret.yaml
mods/d2/rules/heavy_factory.yaml
mods/d2/rules/high_tech_factory.yaml
mods/d2/rules/light_factory.yaml
mods/d2/rules/light_inf.yaml
mods/d2/rules/light_squad.yaml
mods/d2/rules/outpost.yaml
mods/d2/rules/palace.yaml
mods/d2/rules/refinery.yaml
mods/d2/rules/repair_pad.yaml
mods/d2/rules/research_centre.yaml
mods/d2/rules/rocket_turret.yaml
mods/d2/rules/silo.yaml
mods/d2/rules/starport.yaml
mods/d2/rules/trooper.yaml
mods/d2/rules/trooper_squad.yaml
mods/d2/rules/wall.yaml
mods/d2/rules/wind_trap.yaml
mods/d2/rules/wor.yaml

Didn't touch the vehicles yet and i'm not sure if those are really correct, but i used what Nyerguds' D2 Editor says.
It says WOR's prereqs are Windtrap, Outpost, Barracks, but Harkonnen has no Barracks, so i think they should be getting it directly after outpost, ~~again i didn't check by playing original game.~~ Edit: I'm at 3rd Harkonnen mission, that appears to be the case.
I also edited the palette orders, but Ordos having both barracks and WOR isn't helping.

Update prerequisites of structures and infantry

---

mods/d2/rules/combat_tank.yaml
mods/d2/rules/husks.yaml
mods/d2/rules/raider.yaml
mods/d2/rules/starport_items.yaml
mods/d2/weapons/largeguns.yaml
mods/d2/weapons/missiles.yaml
mods/d2/weapons/other.yaml
mods/d2/weapons/smallguns.yaml
mods/d2/weapons/spicebloom.yaml
mods/d2/weapons/squads.yaml

This also merges the combat tanks (there weren't seperate ones in D2) and trike/raider weapon (raider is only move faster not fire faster).
Original game didn't have armor classes, so i removed Versus values, tho not the Armor: traits yet.

Change damage values to original and remove Versus:

---

mods/d2/rules/ai.yaml

Looks like AI wasn't touched at all, so it had leftovers from D2k and wasn't building WOR.

Some AI Fixes

---

mods/d2/sequences/overlay.yaml

Leftover one from D2K looks wierd, even concrete shows itself in placement overlay anyway, so it looks better without it.

Remove the placement overlay

---

mods/d2/rules/player.yaml
mods/d2/rules/world.yaml

D2 mod looks like lacking crates, which makes lobby order wierd. I put worms to place of crates, so locations of other options match other mods.

Reorder lobby options so Worms go to place of Crates.

---

mods/d2/rules/player.yaml
mods/d2/rules/world.yaml

New checkbox added with the new release, DisplayOrder wasn't set with the update so it was showing at the second place.

Reorder lobby options to properly locate SeparateTeamSpawns

---

mods/d2/chrome/ingame-player.yaml
mods/d2/rules/barracks.yaml
mods/d2/rules/construction_yard.yaml
mods/d2/rules/heavy_factory.yaml
mods/d2/rules/high_tech_factory.yaml
mods/d2/rules/light_factory.yaml
mods/d2/rules/light_inf.yaml
mods/d2/rules/light_squad.yaml
mods/d2/rules/player.yaml
mods/d2/rules/starport.yaml
mods/d2/rules/trooper.yaml
mods/d2/rules/trooper_squad.yaml
mods/d2/rules/wor.yaml

Closes #77.
I have removed the Queue buttons on the UI too, as i did on Generals Alpha. UI now have a useless area but still imo it is better this way. For both Generals and Dune 2, you had to select the building itself and making that the case on OpenRA makes the mod more unique.
Also upgrade queue is now gone and every upgrade is on its own building, it still don't work as in original tho. I have the logic to make them work on Generals Alpha engine but that is too hacky to ever get to upstream.

Implement Multi Queue logic.

---

OpenRA.Mods.D2/Traits/D2AffectsShroud.cs

Closes https://github.com/OpenRA/d2/issues/60
Do not use Moving Range then CurrentActivity is Attack or HarvestResource

Correct range for attack and harvesting in D2RevealsShroud

---

OpenRA.Mods.D2/AudioLoaders/D2VocLoader.cs

Closes #99
Current D2VocLoader implementation too strict. it allow to load only VOC files with version 1.10.
Some VOC files can be version 1.20.  Some other versions possibly can be in different PAK files.
Check for major version only. All VOC files version 1.x will be loaded.

Check only major version in VOC files

---

OpenRA.Mods.D2/D2LoadScreen.cs
OpenRA.Mods.D2/D2UnpackContent.cs
OpenRA.Mods.D2/OpenRA.Mods.D2.csproj
mods/d2/audio/voices.yaml
mods/d2/mod.yaml

Closes #95 and Closes #36 
Unpack and rename files needed, because some PAK files can contain sound files with prefix ‘Z’
This pull request will rename such files, and remove prefix ‘Z’. No other changes in yaml or engine needed for this files to play.

Unpack and rename files from PAK file to ‘Content/d2/Unpacked' directory

---

mods/d2/rules/palace.yaml

Not sure if 7500 is correct to original but better 5 mins than instant.

Fix Death Hand Missile charge time

---

mods/d2/cursors.yaml
mods/d2/tilesets/arrakis2.yaml

We don't have a specific cursor for that here and it was using the wrong cursor at the first place.

Remove move-rough cursor.

---

mods/d2/rules/outpost.yaml

The removal of the anim exists in D2k because in D2k radar dish stop spinning when damaged and the actual body contains the damaged dish. We don't have damaged art on D2, so this should go.

Fix outpost dish when damaged.

---

mods/d2/rules/palettes.yaml
mods/d2/rules/powerdown.yaml

Remove disabled palette.
It displays incorrectly on outpost.
powerdown outpost just stop rotating radar.

Remove disabled palette

---

OpenRA.Mods.D2/Traits/World/D2Selection.cs
mods/d2/rules/player.yaml
mods/d2/rules/world.yaml

closes #120 
Add Single Selection and use it by default. But allow to use multi-selection if uncheck ‘Single Selection’ in lobby:

Add Single Selection

---

OpenRA.Mods.D2/Widgets/D2LineWidget.cs
OpenRA.Mods.D2/Widgets/D2PanelWidget.cs
OpenRA.Mods.D2/Widgets/D2ProgressBarWidget.cs
OpenRA.Mods.D2/Widgets/D2SpriteWidget.cs
OpenRA.Mods.D2/Widgets/D2WidgetUtils.cs
OpenRA.Mods.D2/Widgets/Logic/Ingame/D2IngameActorInfoDisplayLogic.cs
mods/d2/chrome/ingame-player.yaml

Closes #124
Add sidebar with information about currently selected unit or building.
Note that sidebar from d2k will be removed, when d2 sidebar will be finished

Add sidebar panel with Actor info

---

mod.config

Need to update with latest modSdk and remove references to Sytem.Drawing from mod.config.
Because of this: https://github.com/OpenRA/d2/issues/140#issuecomment-536227264

Remove reference to System.Drawing from mod.config

---

mod.config
mods/d2/chrome/assetbrowser.yaml
mods/d2/weapons/largeguns.yaml

Next change in d2 (Related to #149) will need changes in OpenRA engine (in Sheet.cs, ChromeProvider.cs and other UI related stuff).
Better to switch to bleed now, and when changes in engine will be merged, just use it from bleed.
Currently bleed contain only two UpdateRules and commit in this PR is trivial.

Update OpenRA engine to bleed 980c1e1 (2019-11-20)

---

mods/d2/rules/world.yaml

Remove ResourceRenderer from world.yaml (keep D2ResourceRenderer only)

---

OpenRA.Mods.D2/Traits/Render/D2LeavesTracks.cs
mods/d2/mod.yaml
mods/d2/rules/harvester.yaml
mods/d2/rules/vechicle.yaml
mods/d2/sequences/tracks.yaml

Closes #184 
Instead of waiting fix in `LeavesTrails` in upstream in OpenRA/OpenRA#18228
Make modified trait for d2 tracks.
In original, tracks do not overlap when vehicle change direction, like on this screenshoot:
But `LeavesTrails` trait can't do like this, it will draw multiple tracks when vechicle rotating on the same position.

Draw tracks like in original
